package com.maohi.software.maohifx.contact.bean;
// Generated 17 d�c. 2015 16:03:18 by Hibernate Tools 4.0.0

import java.util.Date;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

import com.maohi.software.maohifx.common.AnnotatedClass;

/**
 * Customer generated by hbm2java
 */
@Entity
@Table(name = "customer")
public class Customer implements java.io.Serializable, AnnotatedClass {

	private static final long serialVersionUID = 1L;
	private String uuid;
	private Contact contact;
	private Date creationDate;
	private Date updateDate;
	private String code;
	private String href;

	public Customer() {
	}

	public Customer(final Contact contact) {
		this.contact = contact;
	}

	public Customer(final Contact contact, final Date creationDate, final Date updateDate, final String code) {
		this.contact = contact;
		this.creationDate = creationDate;
		this.updateDate = updateDate;
		this.code = code;
	}

	@Column(name = "code", length = 45)
	public String getCode() {
		return this.code;
	}

	@OneToOne(fetch = FetchType.LAZY, cascade = CascadeType.ALL)
	@PrimaryKeyJoinColumn
	public Contact getContact() {
		return this.contact;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "creation_date", length = 19)
	public Date getCreationDate() {
		return this.creationDate;
	}

	@Transient
	public String getHref() {
		return this.href;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_date", length = 19)
	public Date getUpdateDate() {
		return this.updateDate;
	}

	@Override
	@Id

	@Column(name = "uuid", unique = true, nullable = false)
	public String getUuid() {
		return this.uuid;
	}

	public void setCode(final String code) {
		this.code = code;
	}

	public void setContact(final Contact contact) {
		this.contact = contact;
	}

	@Override
	public void setCreationDate(final Date creationDate) {
		this.creationDate = creationDate;
	}

	@Override
	public void setHref(final String aHref) {
		this.href = aHref;
	}

	@Override
	public void setUpdateDate(final Date updateDate) {
		this.updateDate = updateDate;
	}

	@Override
	public void setUuid(final String uuid) {
		this.uuid = uuid;

		if (this.contact != null) {
			this.contact.setUuid(this.uuid);
		}
	}

}
