package com.maohi.software.maohifx.invoice.bean;
// Generated 10 d�c. 2015 13:34:05 by Hibernate Tools 4.0.0

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * InvoicePaymentLine generated by hbm2java
 */
@Entity
@Table(name = "invoice_payment_line")
public class InvoicePaymentLine implements java.io.Serializable {

	private static final long serialVersionUID = 1L;

	private String uuid;
	private Invoice invoice;
	private PaymentMode paymentMode;
	private Date creationDate;
	private Date updateDate;
	private Integer position;
	private Double amount;
	private String comment;

	public InvoicePaymentLine() {
	}

	public InvoicePaymentLine(final String uuid, final Invoice invoice, final PaymentMode paymentMode) {
		this.uuid = uuid;
		this.invoice = invoice;
		this.paymentMode = paymentMode;
	}

	public InvoicePaymentLine(final String uuid, final Invoice invoice, final PaymentMode paymentMode, final Date creationDate, final Date updateDate, final Integer position, final Double amount, final String comment) {
		this.uuid = uuid;
		this.invoice = invoice;
		this.paymentMode = paymentMode;
		this.creationDate = creationDate;
		this.updateDate = updateDate;
		this.position = position;
		this.amount = amount;
		this.comment = comment;
	}

	@Column(name = "amount", precision = 22, scale = 0)
	public Double getAmount() {
		return this.amount;
	}

	@Column(name = "comment")
	public String getComment() {
		return this.comment;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "creation_date", length = 19)
	public Date getCreationDate() {
		return this.creationDate;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "invoice_uuid", nullable = false)
	public Invoice getInvoice() {
		return this.invoice;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "payment_mode", nullable = false)
	public PaymentMode getPaymentMode() {
		return this.paymentMode;
	}

	@Column(name = "position")
	public Integer getPosition() {
		return this.position;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_date", length = 19)
	public Date getUpdateDate() {
		return this.updateDate;
	}

	@Id

	@Column(name = "uuid", unique = true, nullable = false)
	public String getUuid() {
		return this.uuid;
	}

	public void setAmount(final Double amount) {
		this.amount = amount;
	}

	public void setComment(final String comment) {
		this.comment = comment;
	}

	public void setCreationDate(final Date creationDate) {
		this.creationDate = creationDate;
	}

	public void setInvoice(final Invoice invoice) {
		this.invoice = invoice;
	}

	public void setPaymentMode(final PaymentMode paymentMode) {
		this.paymentMode = paymentMode;
	}

	public void setPosition(final Integer position) {
		this.position = position;
	}

	public void setUpdateDate(final Date updateDate) {
		this.updateDate = updateDate;
	}

	public void setUuid(final String uuid) {
		this.uuid = uuid;
	}

}
