package com.maohi.software.maohifx.invoice.bean;
// Generated 10 d�c. 2015 13:34:05 by Hibernate Tools 4.0.0

import java.util.Date;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

/**
 * InvoicePaymentLine generated by hbm2java
 */
@Entity
@Table(name = "invoice_payment_line")
@JsonIgnoreProperties({ "invoice" })
public class InvoicePaymentLine implements java.io.Serializable {

	private static final long serialVersionUID = 1L;

	private String uuid;
	private Invoice invoice;
	private PaymentMode paymentMode;
	private Date creationDate;
	private Date updateDate;
	private Integer position;
	private Double amount;
	private String comment;

	public InvoicePaymentLine() {
	}

	public InvoicePaymentLine(final String uuid, final Invoice invoice, final PaymentMode paymentMode) {
		this.uuid = uuid;
		this.invoice = invoice;
		this.paymentMode = paymentMode;
	}

	public InvoicePaymentLine(final String uuid, final Invoice invoice, final PaymentMode paymentMode, final Date creationDate, final Date updateDate, final Integer position, final Double amount, final String comment) {
		this.uuid = uuid;
		this.invoice = invoice;
		this.paymentMode = paymentMode;
		this.creationDate = creationDate;
		this.updateDate = updateDate;
		this.position = position;
		this.amount = amount;
		this.comment = comment;
	}

	@Override
	public boolean equals(final Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (this.getClass() != obj.getClass()) {
			return false;
		}
		final InvoicePaymentLine other = (InvoicePaymentLine) obj;
		if (this.amount == null) {
			if (other.amount != null) {
				return false;
			}
		} else if (!this.amount.equals(other.amount)) {
			return false;
		}
		if (this.comment == null) {
			if (other.comment != null) {
				return false;
			}
		} else if (!this.comment.equals(other.comment)) {
			return false;
		}
		if (this.creationDate == null) {
			if (other.creationDate != null) {
				return false;
			}
		} else if (!this.creationDate.equals(other.creationDate)) {
			return false;
		}
		if (this.position == null) {
			if (other.position != null) {
				return false;
			}
		} else if (!this.position.equals(other.position)) {
			return false;
		}
		if (this.updateDate == null) {
			if (other.updateDate != null) {
				return false;
			}
		} else if (!this.updateDate.equals(other.updateDate)) {
			return false;
		}
		if (this.uuid == null) {
			if (other.uuid != null) {
				return false;
			}
		} else if (!this.uuid.equals(other.uuid)) {
			return false;
		}
		return true;
	}

	@Column(name = "amount", precision = 22, scale = 0)
	public Double getAmount() {
		return this.amount;
	}

	@Column(name = "comment")
	public String getComment() {
		return this.comment;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "creation_date", length = 19)
	public Date getCreationDate() {
		return this.creationDate;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "invoice_uuid", nullable = false)
	public Invoice getInvoice() {
		return this.invoice;
	}

	@ManyToOne(fetch = FetchType.EAGER, cascade = CascadeType.ALL)
	@JoinColumn(name = "payment_mode", nullable = false)
	public PaymentMode getPaymentMode() {
		return this.paymentMode;
	}

	@Column(name = "position")
	public Integer getPosition() {
		return this.position;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_date", length = 19)
	public Date getUpdateDate() {
		return this.updateDate;
	}

	@Id

	@Column(name = "uuid", unique = true, nullable = false)
	public String getUuid() {
		return this.uuid;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = (prime * result) + ((this.amount == null) ? 0 : this.amount.hashCode());
		result = (prime * result) + ((this.comment == null) ? 0 : this.comment.hashCode());
		result = (prime * result) + ((this.creationDate == null) ? 0 : this.creationDate.hashCode());
		result = (prime * result) + ((this.position == null) ? 0 : this.position.hashCode());
		result = (prime * result) + ((this.updateDate == null) ? 0 : this.updateDate.hashCode());
		result = (prime * result) + ((this.uuid == null) ? 0 : this.uuid.hashCode());
		return result;
	}

	public void setAmount(final Double amount) {
		this.amount = amount;
	}

	public void setComment(final String comment) {
		this.comment = comment;
	}

	public void setCreationDate(final Date creationDate) {
		this.creationDate = creationDate;
	}

	public void setInvoice(final Invoice invoice) {
		this.invoice = invoice;
	}

	public void setPaymentMode(final PaymentMode paymentMode) {
		this.paymentMode = paymentMode;
	}

	public void setPosition(final Integer position) {
		this.position = position;
	}

	public void setUpdateDate(final Date updateDate) {
		this.updateDate = updateDate;
	}

	public void setUuid(final String uuid) {
		this.uuid = uuid;
	}

}
