package com.maohi.software.maohifx.invoice.bean;
// Generated 10 d�c. 2015 13:34:05 by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PaymentMode generated by hbm2java
 */
@Entity
@Table(name = "payment_mode")
public class PaymentMode implements java.io.Serializable {

	private static final long serialVersionUID = 1L;

	private int id;
	private Date creationDate;
	private Date updateDate;
	private String label;
	private Set<InvoicePaymentLine> invoicePaymentLines = new HashSet<>(0);

	public PaymentMode() {
	}

	public PaymentMode(final int id) {
		this.id = id;
	}

	public PaymentMode(final int id, final Date creationDate, final Date updateDate, final String label, final Set<InvoicePaymentLine> invoicePaymentLines) {
		this.id = id;
		this.creationDate = creationDate;
		this.updateDate = updateDate;
		this.label = label;
		this.invoicePaymentLines = invoicePaymentLines;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "creation_date", length = 19)
	public Date getCreationDate() {
		return this.creationDate;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "paymentMode")
	public Set<InvoicePaymentLine> getInvoicePaymentLines() {
		return this.invoicePaymentLines;
	}

	@Column(name = "label")
	public String getLabel() {
		return this.label;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_date", length = 19)
	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setCreationDate(final Date creationDate) {
		this.creationDate = creationDate;
	}

	public void setId(final int id) {
		this.id = id;
	}

	public void setInvoicePaymentLines(final Set<InvoicePaymentLine> invoicePaymentLines) {
		this.invoicePaymentLines = invoicePaymentLines;
	}

	public void setLabel(final String label) {
		this.label = label;
	}

	public void setUpdateDate(final Date updateDate) {
		this.updateDate = updateDate;
	}

}
