package com.maohi.software.maohifx.invoice.bean;
// Generated 18 d�c. 2015 08:18:04 by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.maohi.software.maohifx.common.AnnotatedClass;

/**
 * Tva generated by hbm2java
 */
@Entity
@Table(name = "tva")
@JsonIgnoreProperties({ "invoiceLines" })
public class Tva implements java.io.Serializable, AnnotatedClass {

	private static final long serialVersionUID = 1L;

	private Integer type;
	private Date creationDate;
	private Date updateDate;
	private String label;
	private Double rate;
	private Set<InvoiceLine> invoiceLines = new HashSet<>(0);

	public Tva() {
	}

	public Tva(final Integer type) {
		this.type = type;
	}

	public Tva(final Integer type, final Date creationDate, final Date updateDate, final String label, final Double rate) {
		this.type = type;
		this.creationDate = creationDate;
		this.updateDate = updateDate;
		this.label = label;
		this.rate = rate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "creation_date", length = 19)
	public Date getCreationDate() {
		return this.creationDate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tva", cascade = CascadeType.ALL)
	public Set<InvoiceLine> getInvoiceLines() {
		return this.invoiceLines;
	}

	@Column(name = "label")
	public String getLabel() {
		return this.label;
	}

	@Column(name = "rate", precision = 22, scale = 0)
	public Double getRate() {
		return this.rate;
	}

	@Id

	@Column(name = "type", unique = true, nullable = false)
	public Integer getType() {
		return this.type;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_date", length = 19)
	public Date getUpdateDate() {
		return this.updateDate;
	}

	@Transient
	@Override
	public String getUuid() {
		return null;
	}

	@Override
	public void setCreationDate(final Date creationDate) {
		this.creationDate = creationDate;
	}

	@Override
	public void setHref(final String aHref) {
	}

	public void setInvoiceLines(final Set<InvoiceLine> invoiceLines) {
		this.invoiceLines = invoiceLines;
	}

	public void setLabel(final String label) {
		this.label = label;
	}

	public void setRate(final Double rate) {
		this.rate = rate;
	}

	public void setType(final Integer type) {
		this.type = type;
	}

	@Override
	public void setUpdateDate(final Date updateDate) {
		this.updateDate = updateDate;
	}

	@Override
	public void setUuid(final String aUuid) {
	}

}
