package com.maohi.software.maohifx.product.bean;
// Generated 8 janv. 2016 12:27:52 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ProductPackagingBarcodeId generated by hbm2java
 */
@Embeddable
public class ProductPackagingBarcodeId implements java.io.Serializable {

	private static final long serialVersionUID = 1L;

	private String productPackagingProductUuid;
	private String productPackagingPackagingCode;
	private String barcodeCode;

	public ProductPackagingBarcodeId() {
	}

	public ProductPackagingBarcodeId(final String productPackagingProductUuid, final String productPackagingPackagingCode, final String barcodeCode) {
		this.productPackagingProductUuid = productPackagingProductUuid;
		this.productPackagingPackagingCode = productPackagingPackagingCode;
		this.barcodeCode = barcodeCode;
	}

	@Override
	public boolean equals(final Object other) {
		if ((this == other)) {
			return true;
		}
		if ((other == null)) {
			return false;
		}
		if (!(other instanceof ProductPackagingBarcodeId)) {
			return false;
		}
		final ProductPackagingBarcodeId castOther = (ProductPackagingBarcodeId) other;

		return ((this.getProductPackagingProductUuid() == castOther.getProductPackagingProductUuid()) || ((this.getProductPackagingProductUuid() != null) && (castOther.getProductPackagingProductUuid() != null) && this.getProductPackagingProductUuid().equals(castOther.getProductPackagingProductUuid()))) && ((this.getProductPackagingPackagingCode() == castOther.getProductPackagingPackagingCode()) || ((this.getProductPackagingPackagingCode() != null) && (castOther.getProductPackagingPackagingCode() != null) && this.getProductPackagingPackagingCode().equals(castOther.getProductPackagingPackagingCode()))) && ((this.getBarcodeCode() == castOther.getBarcodeCode()) || ((this.getBarcodeCode() != null) && (castOther.getBarcodeCode() != null) && this.getBarcodeCode().equals(castOther.getBarcodeCode())));
	}

	@Column(name = "barcode_code", nullable = false)
	public String getBarcodeCode() {
		return this.barcodeCode;
	}

	@Column(name = "product_packaging_packaging_code", nullable = false, length = 45)
	public String getProductPackagingPackagingCode() {
		return this.productPackagingPackagingCode;
	}

	@Column(name = "product_packaging_product_uuid", nullable = false)
	public String getProductPackagingProductUuid() {
		return this.productPackagingProductUuid;
	}

	@Override
	public int hashCode() {
		int result = 17;

		result = (37 * result) + (this.getProductPackagingProductUuid() == null ? 0 : this.getProductPackagingProductUuid().hashCode());
		result = (37 * result) + (this.getProductPackagingPackagingCode() == null ? 0 : this.getProductPackagingPackagingCode().hashCode());
		result = (37 * result) + (this.getBarcodeCode() == null ? 0 : this.getBarcodeCode().hashCode());
		return result;
	}

	public void setBarcodeCode(final String barcodeCode) {
		this.barcodeCode = barcodeCode;
	}

	public void setProductPackagingPackagingCode(final String productPackagingPackagingCode) {
		this.productPackagingPackagingCode = productPackagingPackagingCode;
	}

	public void setProductPackagingProductUuid(final String productPackagingProductUuid) {
		this.productPackagingProductUuid = productPackagingProductUuid;
	}

}
