package com.maohi.software.maohifx.product.bean;
// Generated 8 janv. 2016 12:27:52 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ProductPackagingId generated by hbm2java
 */
@Embeddable
public class ProductPackagingId implements java.io.Serializable {

	private static final long serialVersionUID = 1L;

	private String productUuid;
	private String packagingCode;

	public ProductPackagingId() {
	}

	public ProductPackagingId(final String productUuid, final String packagingCode) {
		this.productUuid = productUuid;
		this.packagingCode = packagingCode;
	}

	@Override
	public boolean equals(final Object other) {
		if ((this == other)) {
			return true;
		}
		if ((other == null)) {
			return false;
		}
		if (!(other instanceof ProductPackagingId)) {
			return false;
		}
		final ProductPackagingId castOther = (ProductPackagingId) other;

		return ((this.getProductUuid() == castOther.getProductUuid()) || ((this.getProductUuid() != null) && (castOther.getProductUuid() != null) && this.getProductUuid().equals(castOther.getProductUuid()))) && ((this.getPackagingCode() == castOther.getPackagingCode()) || ((this.getPackagingCode() != null) && (castOther.getPackagingCode() != null) && this.getPackagingCode().equals(castOther.getPackagingCode())));
	}

	@Column(name = "packaging_code", nullable = false, length = 45)
	public String getPackagingCode() {
		return this.packagingCode;
	}

	@Column(name = "product_uuid", nullable = false)
	public String getProductUuid() {
		return this.productUuid;
	}

	@Override
	public int hashCode() {
		int result = 17;

		result = (37 * result) + (this.getProductUuid() == null ? 0 : this.getProductUuid().hashCode());
		result = (37 * result) + (this.getPackagingCode() == null ? 0 : this.getPackagingCode().hashCode());
		return result;
	}

	public void setPackagingCode(final String packagingCode) {
		this.packagingCode = packagingCode;
	}

	public void setProductUuid(final String productUuid) {
		this.productUuid = productUuid;
	}

}
