package com.maohi.software.maohifx.product.bean;
// Generated 15 d�c. 2015 21:01:28 by Hibernate Tools 4.0.0

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

import com.maohi.software.maohifx.common.server.AnnotatedClass;
import com.maohi.software.maohifx.invoice.bean.Tva;

/**
 * Product generated by hbm2java
 */
@Entity
@Table(name = "product")
public class Product implements java.io.Serializable, AnnotatedClass {

	private static final long serialVersionUID = 1L;

	private String uuid;
	private Tva tva;
	private Date creationDate;
	private Date updateDate;
	private String designation;
	private Double sellingPrice;
	private String href;

	public Product() {
	}

	public Product(final String uuid, final Tva tva) {
		this.uuid = uuid;
		this.tva = tva;
	}

	public Product(final String uuid, final Tva tva, final Date creationDate, final Date updateDate, final String designation, final Double sellingPrice) {
		this.uuid = uuid;
		this.tva = tva;
		this.creationDate = creationDate;
		this.updateDate = updateDate;
		this.designation = designation;
		this.sellingPrice = sellingPrice;
	}

	@Override
	public boolean equals(final Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (this.getClass() != obj.getClass()) {
			return false;
		}
		final Product other = (Product) obj;
		if (this.creationDate == null) {
			if (other.creationDate != null) {
				return false;
			}
		} else if (!this.creationDate.equals(other.creationDate)) {
			return false;
		}
		if (this.designation == null) {
			if (other.designation != null) {
				return false;
			}
		} else if (!this.designation.equals(other.designation)) {
			return false;
		}
		if (this.sellingPrice == null) {
			if (other.sellingPrice != null) {
				return false;
			}
		} else if (!this.sellingPrice.equals(other.sellingPrice)) {
			return false;
		}
		if (this.updateDate == null) {
			if (other.updateDate != null) {
				return false;
			}
		} else if (!this.updateDate.equals(other.updateDate)) {
			return false;
		}
		if (this.uuid == null) {
			if (other.uuid != null) {
				return false;
			}
		} else if (!this.uuid.equals(other.uuid)) {
			return false;
		}
		return true;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "creation_date", length = 19)
	public Date getCreationDate() {
		return this.creationDate;
	}

	@Column(name = "designation")
	public String getDesignation() {
		return this.designation;
	}

	@Transient
	public String getHref() {
		return this.href;
	}

	@Column(name = "selling_price", precision = 22, scale = 0)
	public Double getSellingPrice() {
		return this.sellingPrice;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "tva_type", nullable = false)
	public Tva getTva() {
		return this.tva;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_date", length = 19)
	public Date getUpdateDate() {
		return this.updateDate;
	}

	@Override
	@Id

	@Column(name = "uuid", unique = true, nullable = false)
	public String getUuid() {
		return this.uuid;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = (prime * result) + ((this.creationDate == null) ? 0 : this.creationDate.hashCode());
		result = (prime * result) + ((this.designation == null) ? 0 : this.designation.hashCode());
		result = (prime * result) + ((this.sellingPrice == null) ? 0 : this.sellingPrice.hashCode());
		result = (prime * result) + ((this.updateDate == null) ? 0 : this.updateDate.hashCode());
		result = (prime * result) + ((this.uuid == null) ? 0 : this.uuid.hashCode());
		return result;
	}

	@Override
	public void setCreationDate(final Date creationDate) {
		this.creationDate = creationDate;
	}

	public void setDesignation(final String designation) {
		this.designation = designation;
	}

	@Override
	public void setHref(final String href) {
		this.href = href;
	}

	public void setSellingPrice(final Double sellingPrice) {
		this.sellingPrice = sellingPrice;
	}

	public void setTva(final Tva tva) {
		this.tva = tva;
	}

	@Override
	public void setUpdateDate(final Date updateDate) {
		this.updateDate = updateDate;
	}

	@Override
	public void setUuid(final String uuid) {
		this.uuid = uuid;
	}

	@Override
	public String toString() {
		final StringBuilder builder = new StringBuilder();
		builder.append("Product [uuid=");
		builder.append(this.uuid);
		builder.append(", creationDate=");
		builder.append(this.creationDate);
		builder.append(", updateDate=");
		builder.append(this.updateDate);
		builder.append(", designation=");
		builder.append(this.designation);
		builder.append(", sellingPrice=");
		builder.append(this.sellingPrice);
		builder.append("]");
		return builder.toString();
	}

}
