package com.maohi.software.maohifx.product.bean;
// Generated 8 janv. 2016 12:27:52 by Hibernate Tools 4.0.0

import java.util.Date;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

/**
 * ProductPackagingBarcode generated by hbm2java
 */
@Entity
@Table(name = "product_packaging_barcode")
@JsonIgnoreProperties("productPackaging")
public class ProductPackagingBarcode implements java.io.Serializable {

	private static final long serialVersionUID = 1L;

	private ProductPackagingBarcodeId id;
	private Barcode barcode;
	private ProductPackaging productPackaging;
	private Date creationDate;
	private Date updateDate;

	public ProductPackagingBarcode() {
	}

	public ProductPackagingBarcode(final ProductPackagingBarcodeId id, final Barcode barcode, final ProductPackaging productPackaging) {
		this.id = id;
		this.barcode = barcode;
		this.productPackaging = productPackaging;
	}

	public ProductPackagingBarcode(final ProductPackagingBarcodeId id, final Barcode barcode, final ProductPackaging productPackaging, final Date creationDate, final Date updateDate) {
		this.id = id;
		this.barcode = barcode;
		this.productPackaging = productPackaging;
		this.creationDate = creationDate;
		this.updateDate = updateDate;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "barcode_code", nullable = false, insertable = false, updatable = false)
	public Barcode getBarcode() {
		return this.barcode;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "creation_date", length = 19)
	public Date getCreationDate() {
		return this.creationDate;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "productPackagingProductUuid", column = @Column(name = "product_packaging_product_uuid", nullable = false) ), @AttributeOverride(name = "productPackagingPackagingCode", column = @Column(name = "product_packaging_packaging_code", nullable = false, length = 45) ), @AttributeOverride(name = "barcodeCode", column = @Column(name = "barcode_code", nullable = false) ) })
	public ProductPackagingBarcodeId getId() {
		return this.id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumns({ @JoinColumn(name = "product_packaging_product_uuid", referencedColumnName = "product_uuid", nullable = false, insertable = false, updatable = false), @JoinColumn(name = "product_packaging_packaging_code", referencedColumnName = "packaging_code", nullable = false, insertable = false, updatable = false) })
	public ProductPackaging getProductPackaging() {
		return this.productPackaging;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_date", length = 19)
	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setBarcode(final Barcode barcode) {
		this.barcode = barcode;
	}

	public void setCreationDate(final Date creationDate) {
		this.creationDate = creationDate;
	}

	public void setId(final ProductPackagingBarcodeId id) {
		this.id = id;
	}

	public void setProductPackaging(final ProductPackaging productPackaging) {
		this.productPackaging = productPackaging;
	}

	public void setUpdateDate(final Date updateDate) {
		this.updateDate = updateDate;
	}

}
