package com.maohi.software.maohifx.product.bean;
// Generated 14 janv. 2016 09:57:06 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ProductPackagingLotId generated by hbm2java
 */
@Embeddable
public class ProductPackagingLotId implements java.io.Serializable {

	private static final long serialVersionUID = 1L;

	private int lot;
	private String productPackagingPackagingCode;
	private String productPackagingProductUuid;

	public ProductPackagingLotId() {
	}

	public ProductPackagingLotId(final int lot, final String productPackagingPackagingCode, final String productPackagingProductUuid) {
		this.lot = lot;
		this.productPackagingPackagingCode = productPackagingPackagingCode;
		this.productPackagingProductUuid = productPackagingProductUuid;
	}

	@Override
	public boolean equals(final Object other) {
		if ((this == other)) {
			return true;
		}
		if ((other == null)) {
			return false;
		}
		if (!(other instanceof ProductPackagingLotId)) {
			return false;
		}
		final ProductPackagingLotId castOther = (ProductPackagingLotId) other;

		return (this.getLot() == castOther.getLot()) && ((this.getProductPackagingPackagingCode() == castOther.getProductPackagingPackagingCode()) || ((this.getProductPackagingPackagingCode() != null) && (castOther.getProductPackagingPackagingCode() != null) && this.getProductPackagingPackagingCode().equals(castOther.getProductPackagingPackagingCode()))) && ((this.getProductPackagingProductUuid() == castOther.getProductPackagingProductUuid()) || ((this.getProductPackagingProductUuid() != null) && (castOther.getProductPackagingProductUuid() != null) && this.getProductPackagingProductUuid().equals(castOther.getProductPackagingProductUuid())));
	}

	@Column(name = "lot", nullable = false)
	public int getLot() {
		return this.lot;
	}

	@Column(name = "product_packaging_packaging_code", nullable = false, length = 45)
	public String getProductPackagingPackagingCode() {
		return this.productPackagingPackagingCode;
	}

	@Column(name = "product_packaging_product_uuid", nullable = false)
	public String getProductPackagingProductUuid() {
		return this.productPackagingProductUuid;
	}

	@Override
	public int hashCode() {
		int result = 17;

		result = (37 * result) + this.getLot();
		result = (37 * result) + (this.getProductPackagingPackagingCode() == null ? 0 : this.getProductPackagingPackagingCode().hashCode());
		result = (37 * result) + (this.getProductPackagingProductUuid() == null ? 0 : this.getProductPackagingProductUuid().hashCode());
		return result;
	}

	public void setLot(final int lot) {
		this.lot = lot;
	}

	public void setProductPackagingPackagingCode(final String productPackagingPackagingCode) {
		this.productPackagingPackagingCode = productPackagingPackagingCode;
	}

	public void setProductPackagingProductUuid(final String productPackagingProductUuid) {
		this.productPackagingProductUuid = productPackagingProductUuid;
	}

}
