package com.maohi.software.maohifx.product.bean;
// Generated 12 janv. 2016 16:10:22 by Hibernate Tools 4.0.0

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

import com.maohi.software.maohifx.common.server.AnnotatedClass;

/**
 * Tva generated by hbm2java
 */
@Entity
@Table(name = "tva")
public class Tva implements java.io.Serializable, AnnotatedClass {

	private static final long serialVersionUID = 1L;

	private int type;
	private Date creationDate;
	private Date updateDate;
	private String label;
	private Double rate;

	private String href;

	public Tva() {
	}

	public Tva(final int type) {
		this.type = type;
	}

	public Tva(final int type, final Date creationDate, final Date updateDate, final String label, final Double rate) {
		this.type = type;
		this.creationDate = creationDate;
		this.updateDate = updateDate;
		this.label = label;
		this.rate = rate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "creation_date", length = 19)
	public Date getCreationDate() {
		return this.creationDate;
	}

	@Transient
	public String getHref() {
		return this.href;
	}

	@Column(name = "label")
	public String getLabel() {
		return this.label;
	}

	@Column(name = "rate", precision = 22, scale = 0)
	public Double getRate() {
		return this.rate;
	}

	@Id

	@Column(name = "type", unique = true, nullable = false)
	public int getType() {
		return this.type;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_date", length = 19)
	public Date getUpdateDate() {
		return this.updateDate;
	}

	@Transient
	@Override
	public String getUuid() {
		return null;
	}

	@Override
	public void setCreationDate(final Date creationDate) {
		this.creationDate = creationDate;
	}

	@Override
	public void setHref(final String aHref) {
		this.href = aHref;
	}

	public void setLabel(final String label) {
		this.label = label;
	}

	public void setRate(final Double rate) {
		this.rate = rate;
	}

	public void setType(final int type) {
		this.type = type;
	}

	@Override
	public void setUpdateDate(final Date updateDate) {
		this.updateDate = updateDate;
	}

	@Override
	public void setUuid(final String aUuid) {
	}

}
